# Generated by Django 5.1.2 on 2024-10-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astnode',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
